package conversor;

import static org.junit.Assert.*;

import org.junit.Test;

public class TestConversorTemperaturas {

	@Test
	public void testCelsiusAFahrenheit() throws TemperaturaNoValidaException {
		// Crear instancia del SUT (Subject Under Test)
		ConversorTemperaturas conversor = new ConversorTemperaturas();
		
		//assertEquels(valor esperado, valor que se obtiene del método testado, margen de error);
		assertEquals(32, conversor.celsiusAFahrenheit(0), 0);
	}

	@Test
	public void testCelsiusAReamur() throws TemperaturaNoValidaException {
		// Crear instancia del SUT (Subject Under Test)
		ConversorTemperaturas conversor = new ConversorTemperaturas();
		
		//assertEquels(valor esperado, valor que se obtiene del método testado, margen de error);
		assertEquals(0, conversor.celsiusAReamur(0), 0);
	}
	
	//Con que está entre parentesis da error, por que salta la excepción desde el código productivo.
	//Entre parentesis se le avisa que que espera esa excepción
	@Test(expected=TemperaturaNoValidaException.class)
	public void testTemperaturaNoValidaFahrenheit() throws TemperaturaNoValidaException {

		ConversorTemperaturas conversor = new ConversorTemperaturas();

		//Da error por que recibe una excepción desde el código productivo
		conversor.celsiusAFahrenheit(-400);
	}

}
